### ISSUE TITLE
[Bug Report] MiniGrid ViewSizeWrapper doesn't seem to working anymore

### ISSUE THREAD

**Issue by subho406** [Farama-Foundation/Minigrid#311] opened 2023-02-22 23:14 UTC
**Descrption**
Seems like the `ViewSizeWrapper` is not working anymore. I have tried reproducing the results in Google Colab and Mac M1. 

**Code:**
```python
import gymnasium as gym
import matplotlib.pyplot as plt
from minigrid.wrappers import ViewSizeWrapper
import minigrid
env = gym.make("MiniGrid-DoorKey-5x5-v0")
obs, _ = env.reset()
print(obs['image'].shape)

env_obs = ViewSizeWrapper(env, agent_view_size=5)
obs, _ = env_obs.reset()
print(obs['image'].shape)

```

**Output:**
```
(7, 7, 3)
(7, 7, 3)
```

**System Info**
Describe the characteristic of your environment:
 * System info: `22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103 arm64`
 * Python version: 3.9
 ```
gymnasium                                         0.27.1
Minigrid                           2.1.0
```

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/MiniGrid/issues) in the repo (**required**)

**Comment by xixiha5230** [comment] 2023-02-23 14:12
same problem

**Comment by BolunDai0216** [comment] 2023-02-23 14:48
I think the issue is with not using the newest version of `Minigrid`. Can you clone the master branch and see if that solves your issue? 

The issue that you mentioned is resolved in PR#305. Using the newest `Minigrid` version, I get

```console
(7, 7, 3)
(5, 5, 3)
```

after running the code you provided.

**Comment by subho406** [comment] 2023-02-23 23:12
Yes, that works! So the issue was `ViewSizeWrapper` was inheriting the wrong class. Thanks!

**Comment by jbloomAus** [comment] 2023-02-27 22:00
We can probably close this issue since it's solved by the current code?

**Closed** 2023-02-28 14:51 UTC
